

export const base_url = "http:/localhost:5000/api/v1";
export const endPoint ={
    login: '/login',
    register: '/register',
    user: '/user',
    company: '/company-setting',
    site: '/site-setting',
    mail: '/mail-setting',
    otp: '/otp-setting',
    deliveryZone: '/delivery-zones',
    notification: '/notification-setting',
    dashboard: '/dashboard',
    profile: '/profile',
    address: '/address',
    product: '/products',
    category: '/categories',
    brand: '/brands',
    currency: 'currencies',
    unit: '/units',
    tax:'/taxes',
    role:'roles',
    updateProfile: '/update/profile',
    changePassword: '/change/password',
    uploadProfilePic: '/upload/ProfilePic',
    deleteProduct: '/deleteProduct',
    editProduct: '/editProduct',
    getAllProduct: '/getAllProduct',
    getProductById: '/getProductById',
    addToCart: '/addToCart',
    getCart: '/getCart',
    removeFromCart: '/removeFromCart',
    checkout: '/checkout',
    addReview: '/addReview',
    getReviews: '/getReviews',
    getProductsByCategory: '/getProductsByCategory',
    getProductsByBrand: '/getProductsByBrand',
    getProductsByPriceRange: '/getProductsByPriceRange',
    getProductsByRating: '/getProductsByRating',
    getProductsByColor: '/getProductsByColor',
}